job1_all_times:
      tags:
        - dummy
        # must select some runner(s) with runner-tag(s)
      script:
        - echo "job1"
        - date

job2_win:
      tags:
        - dummy
        # must select some runner(s) with runner-tag(s)
      rules:
        - if: $CI_COMMIT_MESSAGE != "CI_NO_WIN"
      script:
        - echo "job2"
        - date
