job1_all_times:
      tags:
        - dummy
        # select some runner(s) by runner-tag(s) - mandatory
        #
      script:
        - echo "job1"
        - date

job2_win:
      tags:
        - dummy
        # select some runner(s) by runner-tag(s) - mandatory
        #
      rules:
        - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_MESSAGE !~ /.*CI_NO_WIN.*/
      script:
        - echo "job2"
        - echo "CI_PIPELINE_SOURCE = $CI_PIPELINE_SOURCE"
        - echo "CI_COMMIT_MESSAGE = $CI_COMMIT_MESSAGE"
        - date
